controller:
  nodeSelector:
    kubernetes.io/hostname: c-nuc7
  
  service:
    type: NodePort
    nodePorts:
      http: 32366
      https: 30197
      tcp:
        25565: 30566

tcp:
  25565: "minecraft-server/minecraft-server-minecraft:25565"
